### ISSUE TITLE
Chinese users can't use self-services normally

### ISSUE THREAD

**Issue by Straysoulight** [deadphoenix8091/bruteforcemovable#4]
Due to certain reasons Google was blocked in Mainland China, so who wants to pass the reCaptcha must use VPN.
The solution is to replace the js path https://www.google.com/recaptcha/api.js introduced by the front-end code with https://recaptcha.net/recaptcha/api.js. After do this, self-service will work normally in China.

**Comment by deadphoenix8091** [comment]
Ive changed the path on the site, however that script also loads content from gstatic (a google service). isnt that blocked too?

**Comment by Straysoulight** [comment]
> Ive changed the path on the site, however that script also loads content from gstatic (a google service). isnt that blocked too?

No, Google's CDN will domain name resolution they local server in China. And that now is working fine. Thank you to solve this issue~

**Comment by Straysoulight** [comment]
Oh wait, seem's like your's subsite not changed, can you change it?

> Ive changed the path on the site, however that script also loads content from gstatic (a google service). isnt that blocked too?

**Comment by deadphoenix8091** [comment]
Afaik the only subsite that also uses recaptcha is fredtool. And ive changed the url on fredtool too. Which subsite do you mean?

**Comment by Straysoulight** [comment]
Oh, sorry. I reopened the issue because the recaptcha service of fredtool seems to be unusable a few days ago. So, thank you again for fix this issue.

> Afaik the only subsite that also uses recaptcha is fredtool. And ive changed the url on fredtool too. Which subsite do you mean?
